version = 0.1

[default.deploy.parameters]
stack_name = "postnl-dks-demo-main"
resolve_s3 = false
s3_prefix = "postnl-dks-demo-main"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "eu-west-1"
